services:
  backend:
    build: .
    container_name: go-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    env_file:
      - .env
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data: